# Generated by Django 4.2.15 on 2024-08-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryPassword',
        ),
    ]
