# Generated by Django 4.0.6 on 2024-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_delete_temporarypassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
