# Generated by Django 4.0.6 on 2024-08-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
    ]
