# Generated by Django 4.0.6 on 2024-08-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_managers_remove_user_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
